# docker-compose up
version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-alternate
    image: ssrspeed
    container_name: ssrspeed
    ports:
       - "10870:10870" 
